backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index_okeybot.md"
        label: "Rocketbots | Chat Automation for All Your Messaging Apps and Live Chat"
        name: index
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
              - {label: "Align Style", name: "align", widget: "select", options: ["horizontal", "vertical"]}
              - {label: "Imagen Hero", name: hero_image, widget: image}
              - {label: "Encabezado Hero", name: heading, widget: string}
              - {label: "Sub Encabezado Hero", name: subheading, widget: string}
              - {label: "Texto Boton Acción Principal", name: hero_buton_text, widget: string}
              - {label: "URL Boton Acción Principal", name: hero_buton_url, widget: string}
              - {label: "Slogan del Hero", name: mainpitch, widget: string}
              - label: "Iconos del Hero"
                name: "hero_icons"
                widget: "list"
                field: {label: Icon, name: icon, widget: image}

          - label: "Características Principales"
            name: main_features
            widget: object
            fields:
              - {label: "Encabezado", name: heading, widget: string}
              - {label: "Sub Encabezado", name: subheading, widget: string}
              - label: "Lista de Características"
                name: "features"
                widget: "list"
                fields: 
                  - {label: Icon, name: icon, widget: image}
                  - {label: "Titulo", name: title, widget: string}
                  - {label: "Descripción", name: "description", widget: "text"}

          - label: "Características Generales"
            name: general_features
            widget: object
            fields:
              - {label: "Lado", name: "align", widget: "select", options: ["left", "right"]}
              - {label: "Clasificación", name: clasification, widget: string}
              - {label: "Enlace", name: link, widget: string}
              - {label: "Título", name: title, widget: string}
              - {label: "Descripción", name: description, widget: text}
              - {label: "Imagen Hero", name: hero_image, widget: image}
              - label: "Lista de Características"
                name: "features"
                widget: "list"
                fields: 
                  - {label: "Texto", name: text, widget: string}


          - label: "Video Introductorio"
            name: video
            widget: object
            fields:
              - {label: "Enlace", name: link, widget: string}
              - {label: "Título", name: title, widget: string}
              - {label: "Descripción", name: description, widget: text}
              - {label: "Imagen del Video", name: video_image, widget: image}
              - label: "Lista de Características"
                name: "video_features"
                widget: "list"
                fields: 
                  - {label: "Titulo", name: text, widget: string}
                  - {label: "Texto", name: text, widget: text}


          - label: "Lista de Clientes"
            name: client_list
            widget: object
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descripción", name: description, widget: text}
              - label: "Lista de Clientes"
                name: "clients"
                widget: "list"
                fields: 
                  - {label: "Enlace", name: link, widget: string}
                  - {label: "Logo", name: logo, widget: image}


      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
